// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: task.sql

package db

import (
	"context"
	"database/sql"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (title, completed, priority, deadline)
VALUES ($1, $2, $3, $4)
RETURNING id, title, completed, created_at, priority, deadline
`

type CreateTaskParams struct {
	Title     string       `json:"title"`
	Completed bool         `json:"completed"`
	Priority  Priority     `json:"priority"`
	Deadline  sql.NullTime `json:"deadline"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.Title,
		arg.Completed,
		arg.Priority,
		arg.Deadline,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Completed,
		&i.CreatedAt,
		&i.Priority,
		&i.Deadline,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks
WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTask, id)
	return err
}

const getAllTasks = `-- name: GetAllTasks :many
SELECT id, title, completed, created_at, priority, deadline FROM tasks
ORDER BY priority
`

func (q *Queries) GetAllTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getAllTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Completed,
			&i.CreatedAt,
			&i.Priority,
			&i.Deadline,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTask = `-- name: GetTask :one
SELECT id, title, completed, created_at, priority, deadline FROM tasks
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTask(ctx context.Context, id int64) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Completed,
		&i.CreatedAt,
		&i.Priority,
		&i.Deadline,
	)
	return i, err
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET
    title = $2,
    completed = $3,
    priority = $4,
    deadline = $5
WHERE id = $1
RETURNING id, title, completed, created_at, priority, deadline
`

type UpdateTaskParams struct {
	ID        int64        `json:"id"`
	Title     string       `json:"title"`
	Completed bool         `json:"completed"`
	Priority  Priority     `json:"priority"`
	Deadline  sql.NullTime `json:"deadline"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTask,
		arg.ID,
		arg.Title,
		arg.Completed,
		arg.Priority,
		arg.Deadline,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Completed,
		&i.CreatedAt,
		&i.Priority,
		&i.Deadline,
	)
	return i, err
}
