// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTask(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateTask'](arg1, arg2, arg3, arg4);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function GetAllTasks() {
  return window['go']['main']['App']['GetAllTasks']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function MarkTaskDone(arg1) {
  return window['go']['main']['App']['MarkTaskDone'](arg1);
}

export function UpdateTask(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateTask'](arg1, arg2, arg3, arg4, arg5);
}
